version: '3.8'

services:

  mysql:
    image:  mysql:8.0.29
    platform: linux/x86_64
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_URL=mysql
      - MYSQL_DB=gennydb
      - MYSQL_PORT=3306
      - MYSQL_ALLOW_EMPTY=
      - MYSQL_DATABASE=gennydb
      - MYSQL_USER=genny
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    # env_file:
    #   - ${ENV_FILE}
    volumes:
      - mysql_data:/var/lib/mysql:delegated
    networks:
      - mainproxy
    ports:
      - 3310:3306
    command: --sql_mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone="+00:00"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  infinispan:
    image: gennyproject/infinispan:14-14
    container_name: infinispan
    hostname: infinispan
    depends_on:
      mysql:
       condition: service_healthy
    ports:
      - 11222:11222
    environment:
        JAVA_OPTS: " -Xms64m -Xmx8192m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=2048m"
        USER: genny
        PASS: password
        ISPN_HOME: /opt/infinispan
        MAKE_DATADIR_WRITABLE: "true"
    volumes:
      - ./infinispan/data/indexes:/opt/infinispan/server/data/indexes
      - ./infinispan/infinispan.xml:/opt/infinispan/server/conf/infinispan.xml
      - ./infinispan/rebuild_index.sh:/opt/infinispan/server/bin/rebuild_index.sh
      - ./infinispan/log4j2.xml:/opt/infinispan/server/conf/log4j2.xml
      - ./infinispan/mysql-connector-java-8.0.28.jar:/opt/infinispan/lib/mysql-connector-java-8.0.28.jar
    networks:
      - mainproxy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11222/rest/v2/cache-managers/default/health/status" ]
      interval: 2s
      timeout: 10s
      retries: 100

volumes:
  mysql_data:
  maildata:
    driver: local
  mailstate:
    driver: local
networks:
  mainproxy:
    name: mp
    driver: bridge

